version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node  # Run as single-node cluster
    ports:
      - "9200:9200"

  logstash:
    image: logstash:7.9.3
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: kibana:7.9.3
    ports:
      - "5601:5601"                # Web UI for exploring logs