name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger on commits to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/service-app:${{ github.sha }} ./service
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/service-app:${{ github.sha }}

      - name: Deploy to GKE
        uses: google-github-actions/deploy-gke@v0
        with:
          cluster: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          manifest: |
            ./k8s/deployment.yaml
            ./k8s/service.yaml
            ./k8s/hpa.yaml
